apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rovo-iot-platform-socketio-ingress
  namespace : rovo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - "agrio.rovo.com"
  rules:
  - host: "agrio.rovo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rovo-iot-platform-service
            port: 
              number: 9092