apiVersion: apps/v1
kind: Deployment
metadata:
  name: rovo-iot-platform-deployment
  namespace: rovo
  # labels:
  #   app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deployment: rovo-iot-platform
  template:
    metadata:
      labels:
        deployment: rovo-iot-platform
    spec:
      containers:
      - name: rovo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
        ports:
            - containerPort: 8080
              protocol: "TCP"
            - containerPort: 9092
              protocol: "TCP"
        startupProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - curl -s -o /dev/null http://localhost:8080/healthcheck && echo ok || echo not_ok
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - curl -s -o /dev/null http://localhost:8080/healthcheck && echo ok || echo not_ok
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - curl -s -o /dev/null http://localhost:8080/healthcheck && echo ok || echo not_ok
          initialDelaySeconds: 30
          periodSeconds: 10
